# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
    - name: Restore dependencies
      run: nuget restore D:\a\twitch-lib\twitch-lib\TwitchLib.csproj
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    - name: Build and Publish Web App
      run: msbuild D:\a\twitch-lib\twitch-lib\TwitchLib.csproj /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: published_library
        path: D:\a\twitch-lib\twitch-lib\bin\Release\NLith*.dll
